namespace: grupp4
images:
  backend: "ghcr.io/morph2k/backend:133a490a8445d42427946343363ca9dbd842acd2"
  frontend: "ghcr.io/morph2k/frontend:4d0aa23be763a4c97b02996b69d4c059d6e709e7"
  postgres: "quay.io/fedora/postgresql-16:latest"
  redis: "quay.io/kurs/redis:latest"
imagePullPolicy: IfNotPresent
replicas:
  backend: 1
  frontend: 1
storage:
  postgresSize: 1Gi
  redisSize: 1Gi
db:
  name: andres-guestbook
secrets:
  dbUser: andres-guestbook
  dbPassword: superhemligt-losen # ändra sen
  redisPassword: annu-mer-hemligt # ändra sen
postgres:
  storage:
    size: 10Gi
    storageClassName: "lvms-vg1"
