apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: andres-guestbook
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://github.com/morph2k/guestbook-argocd.git
    targetRevision: main
    path: helm/guestbook
    helm:
      releaseName: andres-guestbook
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: grupp4

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
