apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: andres-guestbook-cert
  namespace: grupp4
spec:
  secretName: andres-guestbook-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging   # change to prod later
  dnsNames:
    - guestbook-grupp4.apps.devops24.cloud2.se