apiVersion: v1
kind: ConfigMap
metadata:
  name: andres-backend-config
data:
  DB_HOST: "andres-postgres"
  DB_PORT: "5432"
  DB_NAME: "{{ .Values.db.name }}"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: andres-backend-secrets
type: Opaque
stringData:
  DB_USER: "{{ .Values.secrets.dbUser }}"
  DB_PASSWORD: "{{ .Values.secrets.dbPassword }}"
  REDIS_PASSWORD: "{{ .Values.secrets.redisPassword }}"
