apiVersion: v1
kind: ConfigMap
metadata:
  name: andres-backend-config
data:
  DB_NAME: "andres-guestbook"
  DB_HOST: "andres-postgres"
  DB_PORT: "5432"
  REDIS_HOST: "andres-redis"
  REDIS_PORT: "6379"
