apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: andres-guestbook
  namespace: grupp4
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: openshift-default
  tls:
    - hosts:
        - andres-guestbook-grupp4.apps.devops24.cloud2.se
      secretName: andres-guestbook-cert
  rules:
    - host: andres-guestbook-grupp4.apps.devops24.cloud2.se
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: andres-frontend
                port:
                  number: 8080