apiVersion: apps/v1
kind: Deployment
metadata:
  name: andres-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andres-postgres
  template:
    metadata:
      labels:
        app: andres-postgres
    spec:
      containers:
        - name: andres-postgres
          image: {{ .Values.images.postgres }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: andres-backend-secrets
                  key: DB_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: andres-backend-secrets
                  key: DB_PASSWORD
            - name: POSTGRESQL_DATABASE
              value: "{{ .Values.db.name }}"
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: andres-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: andres-postgres
spec:
  selector:
    app: andres-postgres
  ports:
    - port: 5432
      targetPort: 5432
