apiVersion: apps/v1
kind: Deployment
metadata:
  name: andres-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andres-redis
  template:
    metadata:
      labels:
        app: andres-redis
    spec:
      containers:
        - name: andres-redis
          image: {{ .Values.images.redis }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: andres-backend-secrets
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/redis/data
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: andres-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: andres-redis
spec:
  selector:
    app: andres-redis
  ports:
    - port: 6379
      targetPort: 6379
