
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: andres-guestbook
  namespace: grupp4
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  host: "" # l√•t OpenShift generera host
  to:
    kind: Service
    name: andres-frontend
  port:
    targetPort: 8080

  tls:
    termination: edge