{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook
spec:
  to:
    kind: Service
    name: frontend
  port:
    targetPort: 8080
  {{- if .Values.route.host }}
  host: "{{ .Values.route.host }}"
  {{- end }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
  {{- end }}
{{- end }}
